spring:
  application:
    name: ai-prompt-backend
  jackson:
    serialization.WRITE_DATES_AS_TIMESTAMPS: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
  datasource.hikari:
    maximum-pool-size: 5
    minimum-idle: 0
    idle-timeout: 30000
security:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS}

server:
  servlet:
    context-path: /api
openai:
  api-key: ${OPENAI_API_KEY}

  org-id: ${OPENAI_ORG_ID}
  project-id: ${OPENAI_PROJECT_ID}
  base-url: ${OPENAI_BASE_URL}
  model: ${OPENAI_MODEL}

  connect-timeout-ms: 10_000
  read-timeout-ms: 0
  max-retries: 2
app:
  ai:
    model:
      summary: gpt-5-nano
      embedding: text-embedding-3-small
  memory:
    enabled: true
    semantic:
      enabled: true
      topK: 5
    summary:
      maxTokens: 800
      compress-above-tokens: 1200
      tail-messages: 6
    purge:
      enabled: true
      ttlDays: 180

jwt:
  secret: "${JWT_SECRET}"
  expiration-minutes: 15
management.endpoints.web.exposure.include: "health,info,metrics,prometheus"
logging:
  level:
    org.springframework.security: DEBUG
    com.sallyvnge: DEBUG

